name: domain_wc
description: The models and the use cases about PokemonApi.
version: 1.0.0
homepage: https://danielherrerasanchez.tech/

environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
