name: album
description: The models, use cases, infraestructure, and ui about Album.
version: 0.0.1
homepage: https://danielherrerasanchez.tech/

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  google_fonts: 2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

