name: infraestructure_wc
description: A simple fetch to the Pokemon Api
version: 1.0.0
homepage: https://danielherrerasanchez.tech/

environment:
  sdk: '>=2.18.2 <3.0.0'
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  domain_wc: ^1.0.0
  http: ^0.13.5
