name: app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0-223.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  design_system_weincode:
    path: ../design_system_weincode
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/atoms.png
    - assets/images/ufo.png
    - assets/images/alien.png
    - assets/images/metroid.png
    - assets/images/molecules.png
    - assets/images/organisms.png
    - assets/images/templates.png
    - assets/images/pages.png
    - assets/images/foundation.png
    - assets/images/weincode.png
    - assets/images/atoms/image.png
    - assets/images/atoms/imageAsset.png
    - assets/images/atoms/separation.png
    - assets/images/molecules/circleCard.png
    - assets/images/molecules/tileCard.png
    - assets/images/organisms/listOfCards.png
    - assets/images/templates/component.png
    - assets/images/templates/info.png
    - assets/images/pages/success.png
    - assets/images/success.png
