name: super_app
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  design_system_weincode: ^0.0.3
  album:
    path: ../album
  astronomy_daily_data:
    path: ../astronomy_daily_data
  pokemon:
    path: ../pokemon
  flutter_riverpod: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
